#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 17 Secret 
# Url: https://ithelp.ithome.com.tw/articles/10193940
# Licence: MIT
#####################################

apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg
    image: jlptf/privateapp
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regsecret