#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 17 Secret 
# Url: https://ithelp.ithome.com.tw/articles/10193940
# Licence: MIT
#####################################

apiVersion: v1
kind: Pod
metadata:
  name: secret-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /tmp/conf
      name: secret-volume
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
